### ISSUE TITLE
Add target

### ISSUE THREAD

**Issue by Anonymous4045** [letsbuilda/pyweek37#10]
The core idea of the game is the player shoots at a target. I think it'd be simplest to have it be a balloon that pops when hit by a bullet. We need a sprite for a target (could be a template at first) and then collision handling for bullet-on-target. The target should be placed in the map with Tiled. Maybe some maps can also have multiple targets.
```[tasklist]
### Tasks
- [x] Add target sprite
- [x] Place target in Tiled
- [ ] Add collision handler
- [ ] Animate sprite when hit?
- [ ] Check for bullet collision with target
```
